# Task 2: Exploratory Data Analysis
## Ethiopia Financial Inclusion Forecasting

This notebook analyzes patterns in Ethiopia's financial inclusion data: Access (account ownership), Usage (digital payments), infrastructure enablers, and event timelines.

In [1]:
import sys
sys.path.append('..')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from src.data_loader import load_datasets, profile_dataset
from src.eda import (
    dataset_overview, access_analysis, usage_analysis,
    infrastructure_analysis, event_timeline, correlation_analysis,
    impact_link_summary
)

sns.set_theme(style='whitegrid')
%matplotlib inline

## 1. Load Data

In [2]:
df, ref = load_datasets()
print(f'Loaded {len(df)} rows, {len(df.columns)} columns')
df.head()

Loaded 57 rows, 35 columns

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes,parent_id
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Baseline year,NaN,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Gender disaggregated,NaN,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Gender disaggregated,NaN,NaN

In [3]:
parts = profile_dataset(df)

=== All columns (after combining sheets) ===
['record_id', 'record_type', 'category', 'pillar', 'indicator', 'indicator_code', 'indicator_direction', 'value_numeric', 'value_text', 'value_type', 'unit', 'observation_date', 'period_start', 'period_end', 'fiscal_year', 'gender', 'location', 'region', 'source_name', 'source_type', 'source_url', 'confidence', 'related_indicator', 'relationship_type', 'impact_direction', 'impact_magnitude', 'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country', 'collected_by', 'collection_date', 'original_text', 'notes', 'parent_id']

=== Records by record_type ===
record_type
observation    30
impact_link    14
event          10
target          3
Name: count, dtype: int64

=== Records by pillar ===
pillar
ACCESS           20
USAGE            17
NaN              10
GENDER            6
AFFORDABILITY     4
Name: count, dtype: int64

=== Records by source_type ===
source_type
operator      15
NaN           14
survey        10
regulator      7
research       4
policy         3
calculated     2
news           2
Name: count, dtype: int64

=== Records by confidence ===
confidence
high      44
medium    13
Name: count, dtype: int64

=== Temporal range of observations ===
2014-12-31 00:00:00 to 2025-12-31 00:00:00

=== Unique indicators (indicator_code) ===
indicator_code
ACC_OWNERSHIP         6
ACC_FAYDA             3
ACC_MM_ACCOUNT        2
ACC_4G_COV            2
USG_P2P_COUNT         2
GEN_GAP_ACC           2
ACC_MOBILE_PEN        1
USG_P2P_VALUE         1
USG_ATM_COUNT         1
USG_ATM_VALUE         1
USG_CROSSOVER         1
USG_TELEBIRR_USERS    1
USG_TELEBIRR_VALUE    1
USG_MPESA_USERS       1
USG_MPESA_ACTIVE      1
USG_ACTIVE_RATE       1
AFF_DATA_INCOME       1
GEN_MM_SHARE          1
GEN_GAP_MOBILE        1
Name: count, dtype: int64

=== Cataloged events: 10 ===
   record_id record_type        category pillar  \
33  EVT_0001       event  product_launch    NaN
34  EVT_0002       event    market_entry    NaN
35  EVT_0003       event  product_launch    NaN
36  EVT_0004       event  infrastructure    NaN
37  EVT_0005       event          policy    NaN
38  EVT_0006       event       milestone    NaN
39  EVT_0007       event     partnership    NaN
40  EVT_0008       event  infrastructure    NaN
41  EVT_0009       event          policy    NaN
42  EVT_0010       event         pricing    NaN

                                 indicator     indicator_code  \
33                         Telebirr Launch       EVT_TELEBIRR
34    Safaricom Ethiopia Commercial Launch      EVT_SAFARICOM
35                  M-Pesa Ethiopia Launch          EVT_MPESA
36        Fayda Digital ID Program Rollout          EVT_FAYDA
37         Foreign Exchange Liberalization      EVT_FX_REFORM
38     P2P Transaction Count Surpasses ATM      EVT_CROSSOVER
39            M-Pesa EthSwitch Integration  EVT_MPESA_INTEROP
40  EthioPay Instant Payment System Launch       EVT_ETHIOPAY
41                 NFIS-II Strategy Launch          EVT_NFIS2
42       Safaricom Ethiopia Price Increase   EVT_SAFCOM_PRICE

   indicator_direction  value_numeric   value_text   value_type  ...  \
33                 NaN            NaN     Launched  categorical  ...
34                 NaN            NaN     Launched  categorical  ...
35                 NaN            NaN     Launched  categorical  ...
36                 NaN            NaN     Launched  categorical  ...
37                 NaN            NaN  Implemented  categorical  ...
38                 NaN            NaN     Achieved  categorical  ...
39                 NaN            NaN     Launched  categorical  ...
40                 NaN            NaN     Launched  categorical  ...
41                 NaN            NaN     Launched  categorical  ...
42                 NaN            NaN  Implemented  categorical  ...

   impact_magnitude impact_estimate lag_months evidence_basis  \
33              NaN             NaN        NaN            NaN
34              NaN             NaN        NaN            NaN
35              NaN             NaN        NaN            NaN
36              NaN             NaN        NaN            NaN
37              NaN             NaN        NaN            NaN
38              NaN             NaN        NaN            NaN
39              NaN             NaN        NaN            NaN
40              NaN             NaN        NaN            NaN
41              NaN             NaN        NaN            NaN
42              NaN             NaN        NaN            NaN

   comparable_country         collected_by collection_date  \
33    Example_Trainee  2025-01-20 00:00:00             NaN
34    Example_Trainee  2025-01-20 00:00:00             NaN
35    Example_Trainee  2025-01-20 00:00:00             NaN
36    Example_Trainee  2025-01-20 00:00:00             NaN
37    Example_Trainee  2025-01-20 00:00:00             NaN
38    Example_Trainee  2025-01-20 00:00:00             NaN
39    Example_Trainee  2025-01-20 00:00:00             NaN
40    Example_Trainee  2025-01-20 00:00:00             NaN
41    Example_Trainee  2025-01-20 00:00:00             NaN
42    Example_Trainee  2025-01-20 00:00:00             NaN

                                   original_text notes parent_id
33  First major mobile money service in Ethiopia   NaN       NaN
34                 End of state telecom monopoly   NaN       NaN
35                   Second mobile money entrant   NaN       NaN
36          National biometric digital ID system   NaN       NaN
37                         Birr float introduced   NaN       NaN
38       Historic: digital > cash for first time   NaN       NaN
39              Full interoperability for M-Pesa   NaN       NaN
40             National real-time payment system   NaN       NaN
41  5-year national financial inclusion strategy   NaN       NaN
42        Data and voice prices increased 20-82%   NaN       NaN

[10 rows x 35 columns]

=== Impact links: 14 total ===
   record_id  record_type category         pillar  \
43  IMP_0001  impact_link      NaN         ACCESS
44  IMP_0002  impact_link      NaN          USAGE
45  IMP_0003  impact_link      NaN          USAGE
46  IMP_0004  impact_link      NaN         ACCESS
47  IMP_0005  impact_link      NaN  AFFORDABILITY
48  IMP_0006  impact_link      NaN          USAGE
49  IMP_0007  impact_link      NaN         ACCESS
50  IMP_0008  impact_link      NaN         ACCESS
51  IMP_0009  impact_link      NaN         GENDER
52  IMP_0010  impact_link      NaN  AFFORDABILITY

                                     indicator indicator_code  \
43        Telebirr effect on Account Ownership            NaN
44           Telebirr effect on Telebirr Users            NaN
45         Telebirr effect on P2P Transactions            NaN
46             Safaricom effect on 4G Coverage            NaN
47      Safaricom effect on Data Affordability            NaN
48               M-Pesa effect on M-Pesa Users            NaN
49  M-Pesa effect on Mobile Money Account Rate            NaN
50           Fayda effect on Account Ownership            NaN
51                  Fayda effect on Gender Gap            NaN
52      FX Reform effect on Data Affordability            NaN

   indicator_direction  value_numeric value_text  value_type  ...  \
43                 NaN           15.0        NaN  percentage  ...
44                 NaN            NaN        NaN       count  ...
45                 NaN           25.0        NaN  percentage  ...
46                 NaN           15.0        NaN  percentage  ...
47                 NaN          -20.0        NaN  percentage  ...
48                 NaN            NaN        NaN       count  ...
49                 NaN            5.0        NaN  percentage  ...
50                 NaN           10.0        NaN  percentage  ...
51                 NaN           -5.0        NaN      gap_pp  ...
52                 NaN           30.0        NaN  percentage  ...

   impact_magnitude impact_estimate lag_months evidence_basis  \
43             high            15.0       12.0     literature
44             high             NaN        3.0      empirical
45             high            25.0        6.0      empirical
46           medium            15.0       12.0      empirical
47           medium           -20.0       12.0     literature
48             high             NaN        3.0      empirical
49           medium             5.0        6.0    theoretical
50           medium            10.0       24.0     literature
51           medium            -5.0       24.0     literature
52             high            30.0        3.0      empirical

   comparable_country     collected_by      collection_date  original_text  \
43              Kenya  Example_Trainee  2025-01-20 00:00:00            NaN
44                NaN  Example_Trainee  2025-01-20 00:00:00            NaN
45                NaN  Example_Trainee  2025-01-20 00:00:00            NaN
46                NaN  Example_Trainee  2025-01-20 00:00:00            NaN
47             Rwanda  Example_Trainee  2025-01-20 00:00:00            NaN
48                NaN  Example_Trainee  2025-01-20 00:00:00            NaN
49                NaN  Example_Trainee  2025-01-20 00:00:00            NaN
50              India  Example_Trainee  2025-01-20 00:00:00            NaN
51              India  Example_Trainee  2025-01-20 00:00:00            NaN
52                NaN  Example_Trainee  2025-01-20 00:00:00            NaN

                                               notes parent_id
43            Kenya M-Pesa showed +20pp over 5 years  EVT_0001
44                     Direct subscriber acquisition  EVT_0001
45                       New digital payment channel  EVT_0001
46               Network investment from competition  EVT_0002
47              Competition typically reduces prices  EVT_0002
48                     Direct subscriber acquisition  EVT_0003
49         Second provider adds incremental accounts  EVT_0003
50  Aadhaar enabled +15-20% account opening in India  EVT_0004
51      Women disproportionately lack traditional ID  EVT_0004
52      Currency depreciation raises effective costs  EVT_0005

[10 rows x 35 columns]

## 2. Dataset Overview
Temporal coverage and data quality assessment.

In [4]:
obs = dataset_overview(df)

============================================================
1. DATASET OVERVIEW
============================================================

--- record_type x pillar ---
pillar       ACCESS  AFFORDABILITY  GENDER  USAGE
record_type
impact_link       4              3       1      6
observation      14              1       4     11
target            2              0       1      0

Saved: C:\Users\HP EliteBook\Desktop\KAIM\ethiopia-fi-forecast\reports\figures/temporal_coverage.png
Saved: C:\Users\HP EliteBook\Desktop\KAIM\ethiopia-fi-forecast\reports\figures/confidence_distribution.png

--- Sparsest indicators (fewest data points) ---
indicator_code
ACC_MOBILE_PEN     1
AFF_DATA_INCOME    1
GEN_GAP_MOBILE     1
USG_CROSSOVER      1
USG_ATM_VALUE      1
USG_ATM_COUNT      1
USG_ACTIVE_RATE    1
GEN_MM_SHARE       1
dtype: int64

## 3. Access Analysis
Account ownership trajectory, growth rates, and gender gap.

In [5]:
acc = access_analysis(obs)
acc

============================================================
2. ACCESS ANALYSIS
============================================================

--- Account Ownership over time ---
  observation_date  value_numeric
0       2014-12-31           22.0
1       2017-12-31           35.0
2       2021-12-31           46.0
3       2021-12-31           56.0
4       2021-12-31           36.0
5       2024-11-29           49.0

Saved: C:\Users\HP EliteBook\Desktop\KAIM\ethiopia-fi-forecast\reports\figures/access_trajectory.png

--- Growth rate (pp/year) between survey waves ---
  observation_date  pp_change  annualized_pp
0       2014-12-31        NaN            NaN
1       2017-12-31       13.0       4.333333
2       2021-12-31       11.0       2.750000
3       2021-12-31       10.0            inf
4       2021-12-31      -20.0           -inf
5       2024-11-29       13.0       4.333333

--- Gender Gap in Account Ownership ---
   observation_date  value_numeric gender notes
26       2021-12-31           20.0    all   NaN
27       2024-11-29           18.0    all   NaN
Saved: C:\Users\HP EliteBook\Desktop\KAIM\ethiopia-fi-forecast\reports\figures/gender_gap_access.png

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,comparable_country,collected_by,collection_date,original_text,notes,parent_id,year,pp_change,years_elapsed,annualized_pp
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,Example_Trainee,2025-01-20 00:00:00,NaN,Baseline year,NaN,NaN,2014,NaN,NaN,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,Example_Trainee,2025-01-20 00:00:00,NaN,NaN,NaN,NaN,2017,13.0,3.0,4.333333
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,Example_Trainee,2025-01-20 00:00:00,NaN,NaN,NaN,NaN,2021,11.0,4.0,2.750000
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,...,Example_Trainee,2025-01-20 00:00:00,NaN,Gender disaggregated,NaN,NaN,2021,10.0,0.0,inf
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,...,Example_Trainee,2025-01-20 00:00:00,NaN,Gender disaggregated,NaN,NaN,2021,-20.0,0.0,-inf
5,REC_0006,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,49.0,NaN,percentage,...,Example_Trainee,2025-01-20 00:00:00,Account ownership increased from 46% to 49%,Survey Oct-Nov 2024,NaN,NaN,2024,13.0,3.0,4.333333

## 4. Usage (Digital Payments) Analysis

In [6]:
usage = usage_analysis(obs)
usage

============================================================
3. USAGE (DIGITAL PAYMENTS) ANALYSIS
============================================================
        indicator_code observation_date  value_numeric   unit
6       ACC_MM_ACCOUNT       2021-12-31           4.70      %
7       ACC_MM_ACCOUNT       2024-11-29           9.45      %
22     USG_MPESA_USERS       2024-12-31    10800000.00  users
23    USG_MPESA_ACTIVE       2024-12-31     7100000.00  users
24     USG_ACTIVE_RATE       2024-12-31          66.00      %
20  USG_TELEBIRR_USERS       2025-06-30    54840000.00  users
19       USG_CROSSOVER       2025-07-07           1.08  ratio

Saved: C:\Users\HP EliteBook\Desktop\KAIM\ethiopia-fi-forecast\reports\figures/mobile_money_penetration.png

>>> Registered Telebirr users vs. active rate — registered: [54840000.], active_rate: [66.]
>>> Large registered-vs-active gap indicates dormant accounts inflate
    headline registration numbers relative to true usage.

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes,parent_id,year
6,REC_0007,observation,NaN,ACCESS,Mobile Money Account Rate,ACC_MM_ACCOUNT,higher_better,4.70,NaN,percentage,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,NaN,NaN,NaN,2021
7,REC_0008,observation,NaN,ACCESS,Mobile Money Account Rate,ACC_MM_ACCOUNT,higher_better,9.45,NaN,percentage,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Doubled from 2021,NaN,NaN,2024
22,REC_0023,observation,NaN,USAGE,M-Pesa Registered Users,USG_MPESA_USERS,higher_better,10800000.00,NaN,count,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,10.8 million users (+245%),NaN,NaN,NaN,2024
23,REC_0024,observation,NaN,USAGE,M-Pesa 90-Day Active Users,USG_MPESA_ACTIVE,higher_better,7100000.00,NaN,count,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,7.1 million 90-day active,66% activity rate,NaN,NaN,2024
24,REC_0025,observation,NaN,USAGE,Mobile Money Activity Rate,USG_ACTIVE_RATE,higher_better,66.00,NaN,percentage,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,7.1M / 10.8M = 66%,NaN,NaN,2024
20,REC_0021,observation,NaN,USAGE,Telebirr Registered Users,USG_TELEBIRR_USERS,higher_better,54840000.00,NaN,count,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,54.84 million telebirr users,NaN,NaN,NaN,2025
19,REC_0020,observation,NaN,USAGE,P2P/ATM Crossover Ratio,USG_CROSSOVER,higher_better,1.08,NaN,ratio,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,P2P > ATM for first time,NaN,NaN,2025

## 5. Infrastructure & Enablers

In [7]:
infra = infrastructure_analysis(obs)
infra

============================================================
4. INFRASTRUCTURE & ENABLERS
============================================================
     indicator_code observation_date  value_numeric      unit
8        ACC_4G_COV       2023-06-30           37.5         %
11        ACC_FAYDA       2024-08-15      8000000.0    people
25  AFF_DATA_INCOME       2024-12-31            2.0  % of GNI
12        ACC_FAYDA       2025-02-28     12000000.0    people
13        ACC_FAYDA       2025-05-15     15000000.0    people
9        ACC_4G_COV       2025-06-30           70.8         %
10   ACC_MOBILE_PEN       2025-12-31           61.4         %

Saved: C:\Users\HP EliteBook\Desktop\KAIM\ethiopia-fi-forecast\reports\figures/infrastructure_trends.png

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes,parent_id,year
8,REC_0009,observation,NaN,ACCESS,4G Population Coverage,ACC_4G_COV,higher_better,37.5,NaN,percentage,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Before major expansion,NaN,NaN,2023
11,REC_0012,observation,NaN,ACCESS,Fayda Digital ID Enrollment,ACC_FAYDA,higher_better,8000000.0,NaN,count,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,NaN,NaN,NaN,2024
25,REC_0026,observation,NaN,AFFORDABILITY,Data Affordability Index,AFF_DATA_INCOME,lower_better,2.0,NaN,percentage,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Now meets UN 2% target,NaN,NaN,2024
12,REC_0013,observation,NaN,ACCESS,Fayda Digital ID Enrollment,ACC_FAYDA,higher_better,12000000.0,NaN,count,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,Over 12 million registered as of February 2025,NaN,NaN,NaN,2025
13,REC_0014,observation,NaN,ACCESS,Fayda Digital ID Enrollment,ACC_FAYDA,higher_better,15000000.0,NaN,count,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,NaN,NaN,NaN,2025
9,REC_0010,observation,NaN,ACCESS,4G Population Coverage,ACC_4G_COV,higher_better,70.8,NaN,percentage,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,4G coverage doubled from 37.5% to 70.8%,Major infrastructure investment,NaN,NaN,2025
10,REC_0011,observation,NaN,ACCESS,Mobile Subscription Penetration,ACC_MOBILE_PEN,higher_better,61.4,NaN,percentage,...,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,93.7M connections / 152.7M population,NaN,NaN,2025

## 6. Event Timeline & Overlay
Do account ownership / mobile money trends shift around key events (Telebirr launch, M-Pesa entry, Safaricom entry)?

In [8]:
events = event_timeline(df, obs)
events

============================================================
5. EVENT TIMELINE & OVERLAY
============================================================
   record_id        category                               indicator  \
33  EVT_0001  product_launch                         Telebirr Launch
41  EVT_0009          policy                 NFIS-II Strategy Launch
34  EVT_0002    market_entry    Safaricom Ethiopia Commercial Launch
35  EVT_0003  product_launch                  M-Pesa Ethiopia Launch
36  EVT_0004  infrastructure        Fayda Digital ID Program Rollout
37  EVT_0005          policy         Foreign Exchange Liberalization
38  EVT_0006       milestone     P2P Transaction Count Surpasses ATM
39  EVT_0007     partnership            M-Pesa EthSwitch Integration
42  EVT_0010         pricing       Safaricom Ethiopia Price Increase
40  EVT_0008  infrastructure  EthioPay Instant Payment System Launch

   observation_date
33       2021-05-17
41       2021-09-01
34       2022-08-01
35       2023-08-01
36       2024-01-01
37       2024-07-29
38       2024-10-01
39       2025-10-27
42       2025-12-15
40       2025-12-18

Saved: C:\Users\HP EliteBook\Desktop\KAIM\ethiopia-fi-forecast\reports\figures/event_timeline_overlay.png

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes,parent_id
33,EVT_0001,event,product_launch,NaN,Telebirr Launch,EVT_TELEBIRR,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,First major mobile money service in Ethiopia,NaN,NaN
41,EVT_0009,event,policy,NaN,NFIS-II Strategy Launch,EVT_NFIS2,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,5-year national financial inclusion strategy,NaN,NaN
34,EVT_0002,event,market_entry,NaN,Safaricom Ethiopia Commercial Launch,EVT_SAFARICOM,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,End of state telecom monopoly,NaN,NaN
35,EVT_0003,event,product_launch,NaN,M-Pesa Ethiopia Launch,EVT_MPESA,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Second mobile money entrant,NaN,NaN
36,EVT_0004,event,infrastructure,NaN,Fayda Digital ID Program Rollout,EVT_FAYDA,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,National biometric digital ID system,NaN,NaN
37,EVT_0005,event,policy,NaN,Foreign Exchange Liberalization,EVT_FX_REFORM,NaN,NaN,Implemented,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Birr float introduced,NaN,NaN
38,EVT_0006,event,milestone,NaN,P2P Transaction Count Surpasses ATM,EVT_CROSSOVER,NaN,NaN,Achieved,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Historic: digital > cash for first time,NaN,NaN
39,EVT_0007,event,partnership,NaN,M-Pesa EthSwitch Integration,EVT_MPESA_INTEROP,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Full interoperability for M-Pesa,NaN,NaN
42,EVT_0010,event,pricing,NaN,Safaricom Ethiopia Price Increase,EVT_SAFCOM_PRICE,NaN,NaN,Implemented,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,Data and voice prices increased 20-82%,NaN,NaN
40,EVT_0008,event,infrastructure,NaN,EthioPay Instant Payment System Launch,EVT_ETHIOPAY,NaN,NaN,Launched,categorical,...,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20 00:00:00,NaN,National real-time payment system,NaN,NaN

## 7. Correlation Analysis

In [9]:
corr = correlation_analysis(obs)
corr

============================================================
6. CORRELATION ANALYSIS
============================================================
Not enough overlapping indicators for meaningful correlation. Consider interpolation or focus on qualitative event-overlay analysis instead.

## 8. Existing Impact Link Relationships

In [10]:
links = impact_link_summary(df)
links

============================================================
7. IMPACT LINK SUMMARY
============================================================
                            event_name event_category  related_indicator impact_direction impact_magnitude  lag_months evidence_basis confidence
                       Telebirr Launch product_launch      ACC_OWNERSHIP         increase             high        12.0     literature     medium
                       Telebirr Launch product_launch USG_TELEBIRR_USERS         increase             high         3.0      empirical       high
                       Telebirr Launch product_launch      USG_P2P_COUNT         increase             high         6.0      empirical     medium
  Safaricom Ethiopia Commercial Launch   market_entry         ACC_4G_COV         increase           medium        12.0      empirical     medium
  Safaricom Ethiopia Commercial Launch   market_entry    AFF_DATA_INCOME         decrease           medium        12.0     literature     medium
                M-Pesa Ethiopia Launch product_launch    USG_MPESA_USERS         increase             high         3.0      empirical       high
                M-Pesa Ethiopia Launch product_launch     ACC_MM_ACCOUNT         increase           medium         6.0    theoretical     medium
      Fayda Digital ID Program Rollout infrastructure      ACC_OWNERSHIP         increase           medium        24.0     literature     medium
      Fayda Digital ID Program Rollout infrastructure        GEN_GAP_ACC         decrease           medium        24.0     literature     medium
       Foreign Exchange Liberalization         policy    AFF_DATA_INCOME         increase             high         3.0      empirical       high
          M-Pesa EthSwitch Integration    partnership   USG_MPESA_ACTIVE         increase           medium         3.0     literature     medium
          M-Pesa EthSwitch Integration    partnership      USG_P2P_COUNT         increase           medium         3.0     literature     medium
EthioPay Instant Payment System Launch infrastructure      USG_P2P_COUNT         increase           medium         6.0     literature     medium
     Safaricom Ethiopia Price Increase        pricing    AFF_DATA_INCOME         increase              low         1.0      empirical       high

,event_name,event_category,related_indicator,impact_direction,impact_magnitude,lag_months,evidence_basis,confidence
0,Telebirr Launch,product_launch,ACC_OWNERSHIP,increase,high,12.0,literature,medium
1,Telebirr Launch,product_launch,USG_TELEBIRR_USERS,increase,high,3.0,empirical,high
2,Telebirr Launch,product_launch,USG_P2P_COUNT,increase,high,6.0,empirical,medium
3,Safaricom Ethiopia Commercial Launch,market_entry,ACC_4G_COV,increase,medium,12.0,empirical,medium
4,Safaricom Ethiopia Commercial Launch,market_entry,AFF_DATA_INCOME,decrease,medium,12.0,literature,medium
5,M-Pesa Ethiopia Launch,product_launch,USG_MPESA_USERS,increase,high,3.0,empirical,high
6,M-Pesa Ethiopia Launch,product_launch,ACC_MM_ACCOUNT,increase,medium,6.0,theoretical,medium
7,Fayda Digital ID Program Rollout,infrastructure,ACC_OWNERSHIP,increase,medium,24.0,literature,medium
8,Fayda Digital ID Program Rollout,infrastructure,GEN_GAP_ACC,decrease,medium,24.0,literature,medium
9,Foreign Exchange Liberalization,policy,AFF_DATA_INCOME,increase,high,3.0,empirical,high
10,M-Pesa EthSwitch Integration,partnership,USG_MPESA_ACTIVE,increase,medium,3.0,literature,medium
11,M-Pesa EthSwitch Integration,partnership,USG_P2P_COUNT,increase,medium,3.0,literature,medium
12,EthioPay Instant Payment System Launch,infrastructure,USG_P2P_COUNT,increase,medium,6.0,literature,medium
13,Safaricom Ethiopia Price Increase,pricing,AFF_DATA_INCOME,increase,low,1.0,empirical,high